# Generated by Django 2.2.6 on 2019-10-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_cover',
            field=models.ImageField(default='bookcover.jpg', upload_to='bookcovers'),
        ),
    ]
