# Generated by Django 2.2.6 on 2019-10-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191031_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
