# Generated by Django 2.2.6 on 2019-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
