# Generated by Django 2.2.6 on 2019-11-05 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='code',
            field=models.CharField(default='JEY3nhVgZrTRDXuP', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('checking', 'Đang kiểm tra'), ('shipping', 'Đang giao hàng'), ('finished', 'Giao hàng thành công')], default='finished', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
